#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-ggvis
Version  : 0.4.3
Release  : 2
URL      : https://cran.r-project.org/src/contrib/ggvis_0.4.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/ggvis_0.4.3.tar.gz
Summary  : Interactive Grammar of Graphics
Group    : Development/Tools
License  : GPL-2.0
Requires: R-dplyr
Requires: R-htmltools
Requires: R-jsonlite
Requires: R-lazyeval
Requires: R-mime
Requires: R-plyr
Requires: R-shiny
BuildRequires : R-dplyr
BuildRequires : R-htmltools
BuildRequires : R-jsonlite
BuildRequires : R-lazyeval
BuildRequires : R-mime
BuildRequires : R-plyr
BuildRequires : R-shiny
BuildRequires : clr-R-helpers

%description
best parts of 'ggplot2', combining them with the reactive framework of
    'shiny' and drawing web graphics using 'vega'.

%prep
%setup -q -c -n ggvis

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530337265

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1530337265
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ggvis
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ggvis
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ggvis
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library ggvis|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/ggvis/DESCRIPTION
/usr/lib64/R/library/ggvis/INDEX
/usr/lib64/R/library/ggvis/LICENSE
/usr/lib64/R/library/ggvis/Meta/Rd.rds
/usr/lib64/R/library/ggvis/Meta/data.rds
/usr/lib64/R/library/ggvis/Meta/demo.rds
/usr/lib64/R/library/ggvis/Meta/features.rds
/usr/lib64/R/library/ggvis/Meta/hsearch.rds
/usr/lib64/R/library/ggvis/Meta/links.rds
/usr/lib64/R/library/ggvis/Meta/nsInfo.rds
/usr/lib64/R/library/ggvis/Meta/package.rds
/usr/lib64/R/library/ggvis/NAMESPACE
/usr/lib64/R/library/ggvis/NEWS.md
/usr/lib64/R/library/ggvis/R/ggvis
/usr/lib64/R/library/ggvis/R/ggvis.rdb
/usr/lib64/R/library/ggvis/R/ggvis.rdx
/usr/lib64/R/library/ggvis/data/Rdata.rdb
/usr/lib64/R/library/ggvis/data/Rdata.rds
/usr/lib64/R/library/ggvis/data/Rdata.rdx
/usr/lib64/R/library/ggvis/demo/bar.r
/usr/lib64/R/library/ggvis/demo/boxplot.r
/usr/lib64/R/library/ggvis/demo/brush.r
/usr/lib64/R/library/ggvis/demo/dynamic.r
/usr/lib64/R/library/ggvis/demo/guides.r
/usr/lib64/R/library/ggvis/demo/histogram.r
/usr/lib64/R/library/ggvis/demo/hover.r
/usr/lib64/R/library/ggvis/demo/interactive.R
/usr/lib64/R/library/ggvis/demo/lines.r
/usr/lib64/R/library/ggvis/demo/scales.r
/usr/lib64/R/library/ggvis/demo/scatterplot.r
/usr/lib64/R/library/ggvis/demo/size.r
/usr/lib64/R/library/ggvis/demo/smooth.r
/usr/lib64/R/library/ggvis/demo/subvis.R
/usr/lib64/R/library/ggvis/demo/tile.r
/usr/lib64/R/library/ggvis/demo/tourr.r
/usr/lib64/R/library/ggvis/help/AnIndex
/usr/lib64/R/library/ggvis/help/aliases.rds
/usr/lib64/R/library/ggvis/help/ggvis.rdb
/usr/lib64/R/library/ggvis/help/ggvis.rdx
/usr/lib64/R/library/ggvis/help/paths.rds
/usr/lib64/R/library/ggvis/html/00Index.html
/usr/lib64/R/library/ggvis/html/R.css
/usr/lib64/R/library/ggvis/update.sh
/usr/lib64/R/library/ggvis/www/ggvis/css/gear.png
/usr/lib64/R/library/ggvis/www/ggvis/css/ggvis.css
/usr/lib64/R/library/ggvis/www/ggvis/js/ggvis.js
/usr/lib64/R/library/ggvis/www/ggvis/js/shiny-ggvis.js
/usr/lib64/R/library/ggvis/www/lib/d3/d3.js
/usr/lib64/R/library/ggvis/www/lib/d3/d3.min.js
/usr/lib64/R/library/ggvis/www/lib/detect-resize/jquery.resize.js
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/images/ui-bg_diagonals-thick_18_b81900_40x40.png
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/images/ui-bg_diagonals-thick_20_666666_40x40.png
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/images/ui-bg_flat_10_000000_40x100.png
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/images/ui-bg_glass_100_f6f6f6_1x400.png
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/images/ui-bg_glass_100_fdf5ce_1x400.png
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/images/ui-bg_glass_65_ffffff_1x400.png
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/images/ui-bg_gloss-wave_35_f6a828_500x100.png
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/images/ui-bg_highlight-soft_100_eeeeee_1x100.png
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/images/ui-bg_highlight-soft_75_ffe45c_1x100.png
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/images/ui-icons_222222_256x240.png
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/images/ui-icons_228ef1_256x240.png
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/images/ui-icons_ef8c08_256x240.png
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/images/ui-icons_ffd27a_256x240.png
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/images/ui-icons_ffffff_256x240.png
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/index.html
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/jquery-ui.css
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/jquery-ui.js
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/jquery-ui.min.css
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/jquery-ui.min.js
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/jquery-ui.structure.css
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/jquery-ui.structure.min.css
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/jquery-ui.theme.css
/usr/lib64/R/library/ggvis/www/lib/jquery-ui/jquery-ui.theme.min.css
/usr/lib64/R/library/ggvis/www/lib/jquery/AUTHORS.txt
/usr/lib64/R/library/ggvis/www/lib/jquery/jquery.js
/usr/lib64/R/library/ggvis/www/lib/jquery/jquery.min.js
/usr/lib64/R/library/ggvis/www/lib/lodash/lodash.min.js
/usr/lib64/R/library/ggvis/www/lib/vega/vega.js
/usr/lib64/R/library/ggvis/www/lib/vega/vega.min.js
